"""Loop v1 bootstrap runtime primitives."""

from importlib import import_module

from .acceptance import (
    AcceptanceError,
    FinalGateError,
    FinalMergeError,
    FinalReviewError,
    ReadinessError,
    approve_final_request,
    archive_parent_run,
    compute_final_readiness,
    create_final_request,
    execute_final_merge,
    generate_acceptance_pack,
    record_final_review,
)
from .context import (
    EXPECTED_RESULT_FIELDS,
    FRESHNESS_BOUNDARIES,
    ContextError,
    FreshnessError,
    InterventionRequired,
    accept_child_result,
    approve_start_request,
    assert_fresh,
    create_start_request,
    freshness_token,
    intervention_reason,
    issue_child_packet,
    record_context_revision,
)
from .ledger import (
    OPERATION_PHASES,
    LedgerError,
    OperationConflict,
    ParentLedger,
    ProjectionError,
    WriterFenceError,
    WriterLease,
    ledger_path,
)
from .integration import (
    MAX_REPAIR_ROUNDS,
    ControlError,
    IntegrationCASConflict,
    IntegrationError,
    IntegrationStateError,
    ProblemBudgetError,
    RecoveryError,
    acknowledge_integration,
    advance_integration_ref,
    build_integration_candidate,
    cancel_parent,
    cancel_safe_point_status,
    open_recovery_generation,
    pause_parent,
    prepare_integration_candidate,
    reconcile_integration_history,
    reconcile_for_cancel,
    reconcile_parent,
    record_problem_attempt,
    resume_parent,
)
from .scheduler import (
    MAX_PARALLEL,
    SchedulerError,
    deterministic_integration_selection,
    record_optional_omission,
    release_child_resources,
    repair_or_pause_graph,
    requirement_progress,
    schedule_ready,
)
from .task_projection import TaskProjectionError, project_terminal, projection_status
from .task_archive import (
    TaskArchiveError,
    archive_pre_admission_parent,
    retire_task_evidence,
)
from .worker_commit import (
    DirtOverlapError,
    GitStateError,
    ParentValidationError,
    ReviewError,
    WorkerCommitError,
    commit_reviewed_candidate,
    create_child_worktree,
    observe_worker_candidate,
    record_precommit_review,
    scan_repository_dirt,
    validate_child_candidate,
)

_ORCHESTRATOR_EXPORTS = frozenset(
    {
        "OrchestratorError",
        "advance_operator",
        "archive_pre_admission_operator",
        "cancel_safe_point_operator",
        "cancel_operator",
        "continue_recovery",
        "ingest_operator",
        "initialize_operator",
        "operator_status",
        "pause_operator",
        "project_terminal_operator",
        "projection_status_operator",
        "recover_final_checks",
        "reconcile_for_cancel_operator",
        "request_final",
        "request_start",
        "revoke_operator",
        "respond_final",
        "respond_start",
        "retire_task_evidence_operator",
        "resume_operator",
    }
)


def __getattr__(name: str):
    if name in _ORCHESTRATOR_EXPORTS:
        return getattr(import_module(f"{__name__}.orchestrator"), name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "AcceptanceError",
    "EXPECTED_RESULT_FIELDS",
    "FRESHNESS_BOUNDARIES",
    "ContextError",
    "DirtOverlapError",
    "FreshnessError",
    "FinalGateError",
    "FinalMergeError",
    "FinalReviewError",
    "GitStateError",
    "InterventionRequired",
    "IntegrationCASConflict",
    "IntegrationError",
    "IntegrationStateError",
    "MAX_PARALLEL",
    "MAX_REPAIR_ROUNDS",
    "OPERATION_PHASES",
    "LedgerError",
    "OperationConflict",
    "OrchestratorError",
    "ParentLedger",
    "ParentValidationError",
    "ProblemBudgetError",
    "ProjectionError",
    "SchedulerError",
    "TaskProjectionError",
    "TaskArchiveError",
    "ReviewError",
    "ReadinessError",
    "RecoveryError",
    "WorkerCommitError",
    "WriterFenceError",
    "WriterLease",
    "ControlError",
    "acknowledge_integration",
    "advance_operator",
    "accept_child_result",
    "approve_final_request",
    "approve_start_request",
    "archive_parent_run",
    "archive_pre_admission_operator",
    "archive_pre_admission_parent",
    "advance_integration_ref",
    "assert_fresh",
    "create_start_request",
    "create_final_request",
    "create_child_worktree",
    "commit_reviewed_candidate",
    "compute_final_readiness",
    "build_integration_candidate",
    "cancel_parent",
    "cancel_safe_point_operator",
    "cancel_safe_point_status",
    "cancel_operator",
    "continue_recovery",
    "deterministic_integration_selection",
    "freshness_token",
    "execute_final_merge",
    "generate_acceptance_pack",
    "intervention_reason",
    "ingest_operator",
    "initialize_operator",
    "issue_child_packet",
    "ledger_path",
    "observe_worker_candidate",
    "open_recovery_generation",
    "operator_status",
    "pause_parent",
    "pause_operator",
    "project_terminal",
    "project_terminal_operator",
    "projection_status",
    "projection_status_operator",
    "recover_final_checks",
    "prepare_integration_candidate",
    "record_optional_omission",
    "record_problem_attempt",
    "record_precommit_review",
    "record_final_review",
    "record_context_revision",
    "release_child_resources",
    "reconcile_integration_history",
    "reconcile_for_cancel",
    "reconcile_for_cancel_operator",
    "reconcile_parent",
    "repair_or_pause_graph",
    "requirement_progress",
    "request_final",
    "request_start",
    "revoke_operator",
    "respond_final",
    "respond_start",
    "retire_task_evidence",
    "retire_task_evidence_operator",
    "resume_parent",
    "resume_operator",
    "schedule_ready",
    "scan_repository_dirt",
    "validate_child_candidate",
]
