#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from common.paths import get_developer, get_repo_root, get_tasks_dir
from common.tasks import children_progress, get_all_statuses, iter_active_tasks


def task_mtime(task_dir: Path) -> float:
    latest = task_dir.stat().st_mtime
    for path in task_dir.rglob("*"):
        try:
            if path.is_file():
                latest = max(latest, path.stat().st_mtime)
        except OSError:
            continue
    return latest


def fmt_time(ts: float) -> str:
    return datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")


def state(task: object) -> str:
    raw = getattr(task, "raw", {}) or {}
    machine = (raw.get("meta") or {}).get("state_machine") or {}
    return machine.get("current_state") or raw.get("status") or "unknown"


def is_blocked(task: object) -> bool:
    value = state(task).lower()
    return "blocked" in value or getattr(task, "status", "") == "blocked"


def is_waiting(task: object) -> bool:
    return state(task) == "child_waiting_completion_signal"


def active_cards(tasks_dir: Path) -> list[object]:
    return [
        task
        for task in iter_active_tasks(tasks_dir)
        if task.status not in {"completed", "cancelled"}
    ]


def recent_archives(tasks_dir: Path, days: int = 7) -> list[tuple[str, str, float]]:
    archive = tasks_dir / "archive"
    if not archive.is_dir():
        return []
    cutoff = datetime.now().timestamp() - timedelta(days=days).total_seconds()
    rows: list[tuple[str, str, float]] = []
    for task_json in archive.glob("*/*/task.json"):
        try:
            data = json.loads(task_json.read_text(encoding="utf-8"))
            ts = task_mtime(task_json.parent)
        except (OSError, json.JSONDecodeError):
            continue
        if ts >= cutoff:
            rows.append((task_json.parent.name, data.get("status", "completed"), ts))
    return sorted(rows, key=lambda row: row[2], reverse=True)


def build_board(repo_root: Path) -> str:
    tasks_dir = get_tasks_dir(repo_root)
    statuses = get_all_statuses(tasks_dir)
    active = active_cards(tasks_dir)
    waiting = [task for task in active if is_waiting(task)]
    cutoff = datetime.now().timestamp() - timedelta(hours=48).total_seconds()
    stale = [task for task in active if task_mtime(task.directory) < cutoff]
    archives = recent_archives(tasks_dir)
    owner = get_developer(repo_root) or "unknown"

    lines = [
        "# BOARD",
        "",
        "Generated by `.trellis/scripts/board.py`.",
        "",
        f"owner={owner}",
        "",
        "## Active Cards",
        "",
        "| Task | Tier | Owner | Status | Updated | Blocked |",
        "|---|---|---|---|---|---|",
    ]
    if active:
        for task in active:
            raw = task.raw or {}
            progress = children_progress(task.children, statuses)
            name = f"{task.dir_name}{progress}"
            lines.append(
                "| {name} | {tier} | {owner} | {status} | {updated} | {blocked} |".format(
                    name=name,
                    tier=raw.get("tier") or "-",
                    owner=raw.get("owner") or task.assignee or "-",
                    status=task.status,
                    updated=fmt_time(task_mtime(task.directory)),
                    blocked="yes" if is_blocked(task) else "no",
                )
            )
    else:
        lines.append("| - | - | - | - | - | - |")

    lines += ["", "## Waiting For Acceptance", ""]
    if waiting:
        lines += [f"- {task.dir_name} ({state(task)})" for task in waiting]
    else:
        lines.append("- none")

    lines += ["", "## Stale Nudges (>48h)", ""]
    if stale:
        lines += [f"- {task.dir_name} last changed {fmt_time(task_mtime(task.directory))}" for task in stale]
    else:
        lines.append("- none")

    lines += ["", "## Recent Archives (7d)", ""]
    if archives:
        for name, status, ts in archives[:20]:
            lines.append(f"- {name} ({status}, {fmt_time(ts)})")
    else:
        lines.append("- none")

    return "\n".join(lines).rstrip() + "\n"


def build_summary(repo_root: Path, max_lines: int) -> str:
    tasks_dir = get_tasks_dir(repo_root)
    active = active_cards(tasks_dir)
    waiting = [task for task in active if is_waiting(task)]
    cutoff = datetime.now().timestamp() - timedelta(hours=48).total_seconds()
    stale = [task for task in active if task_mtime(task.directory) < cutoff]
    archives = recent_archives(tasks_dir)
    owner = get_developer(repo_root) or "unknown"

    def names(tasks: list[object], limit: int = 3) -> str:
        if not tasks:
            return "none"
        values = [task.dir_name for task in tasks[:limit]]
        return ", ".join(values) + (" ..." if len(tasks) > limit else "")

    lines = [
        f"owner={owner}",
        f"BOARD active={len(active)} waiting={len(waiting)} stale={len(stale)} recent_archives={len(archives)}",
        f"Active: {names(active)}",
        f"Waiting: {names(waiting)}",
        f"Stale >48h: {names(stale)}",
    ]
    if archives:
        lines.append("Recent archives: " + ", ".join(name for name, _, _ in archives[:3]))
    return "\n".join(lines[: max(1, max_lines)])


def write_if_changed(path: Path, content: str) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Trellis BOARD.md")
    parser.add_argument("--summary", action="store_true", help="print compact session summary")
    parser.add_argument("--max-lines", type=int, default=10, help="summary line cap")
    args = parser.parse_args(argv)

    repo_root = get_repo_root()
    if args.summary:
        print(build_summary(repo_root, args.max_lines))
        return 0

    write_if_changed(repo_root / "BOARD.md", build_board(repo_root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
