"""Non-default TaskRun authority, operator, and status-only close primitives."""

from .authority import (
    EventConflict,
    InvalidTransition,
    OperationConflict,
    TaskRun,
    TaskRunError,
    build_final_request,
    read_legacy_task_evidence,
    taskrun_path,
)
from .close import (
    FAULT_BOUNDARIES,
    CloseError,
    CloseUnknownOutcome,
    InjectedFailure,
    close_task_run,
)
from .execution import (
    DECISIONS,
    RESULT_FIELDS,
    STRATEGIES,
    ExecutionError,
    InterventionRequired,
    adapt_loop_result,
    bootstrap_task_run,
    ingest_action_result,
    issue_final_request,
    issue_strategy_actions,
    plan,
    record_action_review_and_reduce,
    record_final_acceptance,
    record_final_candidate_review,
    reduce,
    resume_execution,
    validate_action_result,
    validate_action_review,
)
from .operator import (
    MaterialDriftError,
    OperatorError,
    TaskRunOperator,
    taskrun_id_for_task,
)

__all__ = [
    "FAULT_BOUNDARIES",
    "CloseError",
    "CloseUnknownOutcome",
    "DECISIONS",
    "EventConflict",
    "ExecutionError",
    "InjectedFailure",
    "InterventionRequired",
    "InvalidTransition",
    "MaterialDriftError",
    "OperatorError",
    "OperationConflict",
    "RESULT_FIELDS",
    "STRATEGIES",
    "TaskRun",
    "TaskRunError",
    "TaskRunOperator",
    "adapt_loop_result",
    "bootstrap_task_run",
    "build_final_request",
    "close_task_run",
    "ingest_action_result",
    "issue_final_request",
    "issue_strategy_actions",
    "plan",
    "read_legacy_task_evidence",
    "record_action_review_and_reduce",
    "record_final_acceptance",
    "record_final_candidate_review",
    "reduce",
    "resume_execution",
    "taskrun_path",
    "taskrun_id_for_task",
    "validate_action_result",
    "validate_action_review",
]
